TITLE := $(notdir $(shell pwd))

LY := $(TITLE).ly 
PDF := $(TITLE).pdf

default: $(PDF)

.PHONY: dist
dist: $(LY)
	lilypond -dno-point-and-click $<

$(PDF): $(LY)
	lilypond $<

.PHONY: clean
clean:
	rm -f *.pdf
